// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://embhdlvbudyotfiflwtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtYmhkbHZidWR5b3RmaWZsd3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTk4MzcsImV4cCI6MjA2Mzk3NTgzN30.kz_0QO4rgiqy_zJeZNL8Ii9LX7lTPmt70jbe4I7p3w4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);